name       : kio-gdrive
version    : 1.2.4
release    : 3
source     :
    - https://cdn.download.kde.org/stable/kio-gdrive/1.2.4/src/kio-gdrive-1.2.4.tar.xz : ba903a5bf3b538d42a09bf4d6192e9f06f7e1f80bf5cb4b5c7163b251142c0fc
license    : GPL-2.0-or-later
component  : kde.desktop
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(gl)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Core)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kcalcore-devel
    - kcontacts-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - libkgapi-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
