name       : kio-gdrive
version    : 22.04.3
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kio-gdrive-22.04.3.tar.xz : 621a53b9dff22bea57c3f6e7f8a880e6c90695db7842815817f9e3c39b603a41
license    : GPL-2.0-or-later
component  : kde.desktop
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt5)
    - kaccounts-integration-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkgapi-devel
    - qtkeychain-devel
    - purpose-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
