name       : kio-gdrive
version    : 21.12.1
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kio-gdrive-21.12.1.tar.xz : 468a92aff34725fa3a871b25a40a04d12892aa9cb52e504c9ca5ce70abc81405
license    : GPL-2.0-or-later
component  : kde.desktop
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt5)
    - kaccounts-integration-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkgapi-devel
    - qtkeychain-devel
    - purpose-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
