name       : kio-gdrive
version    : 21.12.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kio-gdrive-21.12.0.tar.xz : b2c3e280a852e0210ce89056ac975a27f74a24d49b4629127384aa87cc084d7b
license    : GPL-2.0-or-later
component  : kde.desktop
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt5)
    - kaccounts-integration-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkgapi-devel
    - qtkeychain-devel
    - purpose-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
