name       : kio-gdrive
version    : 22.08.3
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kio-gdrive-22.08.3.tar.xz : 2e2f862c5a3a340f0f18fed5de3c942095dfd3ee32a97a3666c61e7cf40db69d
license    : GPL-2.0-or-later
component  : kde.desktop
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt5)
    - kaccounts-integration-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkgapi-devel
    - qtkeychain-devel
    - purpose-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
