name       : kio-gdrive
version    : 1.2.5
release    : 4
source     :
    - https://cdn.download.kde.org/stable/kio-gdrive/1.2.5/src/kio-gdrive-1.2.5.tar.xz : 1523c87f3f679cecbef0a2158a133f84379a0b276000c0233c34041b9c14d605
license    : GPL-2.0-or-later
component  : kde.desktop
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(gl)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Core)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kcalcore-devel
    - kcontacts-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - libkgapi-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
