name       : kio-gdrive
version    : 21.04.2
release    : 25
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kio-gdrive-21.04.2.tar.xz : f8645ade66ff647d88c894bb948a4234e3fe0bb5bb462c961375518b47c34e12
license    : GPL-2.0-or-later
component  : kde.desktop
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt5)
    - kaccounts-integration-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
