name       : kio-gdrive
version    : 20.12.1
release    : 19
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/kio-gdrive-20.12.1.tar.xz : e07ef1431b2d9b7e12d9c09483c31f1f321351fc88177d1450d7b18c4640b02b
license    : GPL-2.0-or-later
component  : kde.desktop
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Core)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwindowsystem-devel
    - libkgapi-devel
    - qtkeychain-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
