name       : kio-gdrive
version    : 23.04.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/kio-gdrive-23.04.0.tar.xz : 3998ee8ad380ccc90963e2439674c692e9ee8495ae775b6486e55476785b5442
license    : GPL-2.0-or-later
component  : kde.desktop
summary    : KIO access for Google Drive
description: |
    KIO GDrive enables KIO-aware applications (such as Dolphin, Kate or Gwenview) to access and edit Google Drive files on the cloud.
builddeps  :
    - pkgconfig(accounts-qt5)
    - kaccounts-integration-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - libkgapi-devel
    - qtkeychain-devel
    - purpose-devel
rundeps    :
    - kaccounts-providers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
